#
# HEALTHY AI LAB
#

title: Healthy AI Lab
email: fredrik.johansson@chalmers.se
description: >- # this means to ignore newlines until "baseurl:"
  Healthy AI lab: Research in machine learning and healthcare
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.healthyai.se" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  healthy-ai
future: true
timezone: Europe/Amsterdam
person-default-image: /assets/people/default.png

include: ['_people']

plugins:
  - jekyll-feed
  - jekyll-seo-tag
